---
kind: auto.CommandConfig
name: integration-test
spec:
  disableImage: true
---
kind: common.Docker
spec:
  dockerResourceRequests:
    cpu: 24000
    memory: 48GiB
---
kind: auto.CustomSteps
spec:
  steps:
    - name: $(ARTIFACTS)/$(TALOS_RELEASE)/%
    - name: $(ARTIFACTS)/$(TALOS_RELEASE)
      inputs:
        - $(ARTIFACTS)/$(TALOS_RELEASE)/%
    - name: talos-artifacts
      inputs:
        - $(ARTIFACTS)/$(TALOS_RELEASE)
    - name: run-integration-test
      toplevel: true
      inputs:
        - talos-artifacts
        - integration-test
---
kind: custom.Step
name: $(ARTIFACTS)/$(TALOS_RELEASE)/%
spec:
  makefile:
    enabled: true
    script:
      - >-
        @mkdir -p $(ARTIFACTS)/$(TALOS_RELEASE)/
      - >-
        @curl -L -o "$(ARTIFACTS)/$(TALOS_RELEASE)/$*" "https://github.com/talos-systems/talos/releases/download/$(TALOS_RELEASE)/$*"
---
kind: custom.Step
name: $(ARTIFACTS)/$(TALOS_RELEASE)
spec:
  makefile:
    enabled: true
    phony: true
    depends:
      - $(ARTIFACTS)/$(TALOS_RELEASE)/vmlinuz
      - $(ARTIFACTS)/$(TALOS_RELEASE)/initramfs.xz
      - $(ARTIFACTS)/$(TALOS_RELEASE)/talosctl-linux-amd64
---
kind: custom.Step
name: talos-artifacts
spec:
  makefile:
    enabled: true
    phony: true
    depends:
      - $(ARTIFACTS)/$(TALOS_RELEASE)
    variables:
      - name: TALOS_RELEASE
        defaultValue: v0.7.0-alpha.1
---
kind: custom.Step
name: run-integration-test
spec:
  makefile:
    enabled: true
    phony: true
    depends:
      - talos-artifacts
    script:
      - >-
        @ARTIFACTS=$(ARTIFACTS) TALOS_RELEASE=$(TALOS_RELEASE) ./hack/test/integration-test.sh
  drone:
    enabled: true
    privileged: true
